import { Link } from "react-router-dom";
import React from "react";

import anyBrowser from "../../Images/anybrowser.gif";
import resourcesRendered from "../resources";
import inspirationsRendered from "../inspirations";

function ProfSite(props) {
  return (
    <div className="professor-site">
      <h1 className="centered-text">Aatmnirbhar</h1>
      <hr />
      <div className="greyBox">
        <p>
          I made this club to help students who were interested primarily in
          Software Engineering, by guiding them to the point where they could
          learn things off the internet <b>independently</b>; hence "Aatm (self)
          nirbhar (dependent)". I did this because I was tired of seeing so many
          students go for outsourced and contract-based software development
          jobs in name-and-shame'd firms like{" "}
          <a href="https://www.reddit.com/r/cscareerquestions/comments/eu88if/name_and_shame_tata_consultancy_services/">
            TCS
          </a>
          . I wanted to get a couple of capable students out of "
          <a href="https://www.reddit.com/r/learnprogramming/comments/qrlx5m/what_exactly_is_tutorial_hell/">
            tutorial hell
          </a>
          " and teach them enough so that they could branch out of just
          following tutorials and start their own projects, ones they'd actually
          want to create.
        </p>
      </div>
      <hr />
      <div className="greyBox" id="disclaimer">
        <b>A tiny note:</b> I have recently been looking for MSc supervisors and
        have thus looked at a <b>LOT</b> of websites made by professors. I tried
        to imitate a website that a professor would make for their research
        group... ish. It is an art that I can't replicate!
      </div>
      <hr />
      <div>
        Some useful links:
        <p>
          <Link to="/joinUsProf">Study with us!</Link>
        </p>
        <p>
          <Link to="/peopleProf">People - The Aatmnirbhar team</Link>
        </p>
      </div>
      <h2>Resources</h2>
      <div id="resourcesList">{resourcesRendered}</div>
      <div>
        <p>
          <i>Yug Gajjar</i>
        </p>
        <p>
          <small className="monospace-font">yug.gjr@gmail.com</small>
        </p>
        <p>000-111-2222 (home)</p>
        <p>333-444-5555 (FAX)</p>
        <p>
          <small>
            But please use email, as I'm not even sure the phone still works.
          </small>
        </p>
        <img src={anyBrowser} alt="anyBrowser" id="anyBrowser" />
        <hr />
        <div className="greyBox">
          <p>This site was mostly inspired by:</p>
          <ul>{inspirationsRendered}</ul>
        </div>
        <hr />
        <div className="greyBox">
          The background color of this website is a bit of a mystery to me. I
          don't know why it's so dark, but I do know that it's a dark blue.
          {" <--"} This was generated by GitHub CoPilot.
        </div>
      </div>
    </div>
  );
}

export default ProfSite;
